name: Environments
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: windows-latest  
    environment: Test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Script
      run: echo "ciao" 

    - name: Run node build process
      run: echo '${{ env.ENVIRONMENT_NAME }}'

    - name: Run node build process2
      run: echo "${{ env.ENVIRONMENT_NAME }}"

    - name: Run node build process3
      run: echo '${{ vars.ENVIRONMENT_NAME }}'

    - name: Run node build process24
      run: echo "${{ vars.ENVIRONMENT_NAME }}"


    - name: Use environment variable  
      run: echo 'Deploying to ${$ENVIRONMENT_URL}'  
      env:  
        ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }} # Access the environment variable  
    
